<a href="https://colab.research.google.com/github/Kaveeshamalindi/ANN-Model-for-Mobile-Phone-Price-Prediction/blob/main/ANN_Model_for_Mobile_Phone_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Install TensorFlow

In [4]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.4.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.7.0)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from tensorflow) (80.10.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.6.0)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl (572.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.9/572.9 MB 773.5 kB/s eta 0:00:00
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.4 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 81.4 MB/s eta 0:00:00
Downloading wheel-0.48.0-py3-none-any.whl (33 kB)
Installing collected packages: libclang, flatbuffers, wheel, google_pasta, astunparse, tensorflow
Successfully installed astunparse-1.6.3 flatbuffers-25.12.19 google_pasta-0.2.0 libclang-18.1.1 tensorflow-2.21.0 wheel-0.48.0

## Upload your CSV dataset

In [5]:
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

/usr/local/lib/python3.13/dist-packages/jax/_src/cloud_tpu_init.py:86: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(

In [6]:
import os

os.listdir()

['.config', '.ipynb_checkpoints', 'sample_data']

In [9]:
import os

print(os.listdir("/content/sample_data"))

['anscombe.json', 'README.md', '.ipynb_checkpoints', 'mobile_price.csv', 'california_housing_train.csv', 'mnist_train_small.csv', 'mnist_test.csv', 'california_housing_test.csv']

## Read the CSV file

In [10]:
data = pd.read_csv("/content/sample_data/mobile_price.csv")

In [11]:
data.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,0
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,0
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [13]:
data.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [15]:
data.shape #2000 rows and 21 columns.

(2000, 21)

## Check the target column

In [16]:
data["price_range"].value_counts()

price_range
1    1000
0    1000
Name: count, dtype: int64

## Separate input and output
* X = mobile phone features
* y = price class

In [17]:
X = data.drop("price_range", axis=1)
y = data["price_range"]

## Split the dataset 75% / 25%

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [19]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (1500, 20)
Testing data: (500, 20)

## Scale the features
* ANNs generally work better when numerical features are on similar scales.
* `fit_transform()` only on the training data and `transform()` on the test data. This prevents information from the test set leaking into training.

In [20]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Create the ANN
* 1st hidden layer → 8 neurons
* 2nd hidden layer → 4 neurons

In [21]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),

    tf.keras.layers.Dense(8, activation="relu"),

    tf.keras.layers.Dense(4, activation="relu"),

    tf.keras.layers.Dense(1, activation="sigmoid")
])

## View the ANN architecture

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │           168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209 (836.00 B)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

## Compile the model

In [23]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

## Train the ANN
* 100 epochs
* Batch size = 32

In [24]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

Epoch 1/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5213 - loss: 0.7894 - val_accuracy: 0.5100 - val_loss: 0.7955
Epoch 2/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5460 - loss: 0.7179 - val_accuracy: 0.4940 - val_loss: 0.7537
Epoch 3/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5720 - loss: 0.6838 - val_accuracy: 0.5160 - val_loss: 0.7323
Epoch 4/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5867 - loss: 0.6638 - val_accuracy: 0.5420 - val_loss: 0.7183
Epoch 5/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6495 - val_accuracy: 0.5520 - val_loss: 0.7079
Epoch 6/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6240 - loss: 0.6378 - val_accuracy: 0.5640 - val_loss: 0.6963
Epoch 7/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6380 - loss: 0.6268 - val_accuracy: 0.5720 - val_loss: 0.6903
Epoch 8/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6373 - loss: 0.6170 - val_accuracy: 0.5740 - val_loss: 0.6816
Epoch 9/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6460 - loss: 0.6079 - val_accuracy: 0.5780 - val_loss: 0.6736
Epoch 10/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6001 - val_accuracy: 0.5860 - val_loss: 0.6692
Epoch 11/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6540 - loss: 0.5928 - val_accuracy: 0.5940 - val_loss: 0.6633
Epoch 12/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6587 - loss: 0.5873 - val_accuracy: 0.6020 - val_loss: 0.6600
Epoch 13/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6567 - loss: 0.5820 - val_accuracy: 0.6120 - val_loss: 0.6541
Epoch 14/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6573 - loss: 0.5773 - val_accuracy: 0.6140 - val_loss: 0.6506
Epoch 15/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6553 - loss: 0.5736 - val_accuracy: 0.6200 - val_loss: 0.6477
Epoch 16/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6573 - loss: 0.5697 - val_accuracy: 0.6200 - val_loss: 0.6446
Epoch 17/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6560 - loss: 0.5664 - val_accuracy: 0.6200 - val_loss: 0.6408
Epoch 18/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6580 - loss: 0.5628 - val_accuracy: 0.6240 - val_loss: 0.6383
Epoch 19/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6573 - loss: 0.5594 - val_accuracy: 0.6220 - val_loss: 0.6365
Epoch 20/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6627 - loss: 0.5558 - val_accuracy: 0.6180 - val_loss: 0.6353
Epoch 21/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6620 - loss: 0.5531 - val_accuracy: 0.6220 - val_loss: 0.6345
Epoch 22/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6620 - loss: 0.5496 - val_accuracy: 0.6220 - val_loss: 0.6308
Epoch 23/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6633 - loss: 0.5467 - val_accuracy: 0.6200 - val_loss: 0.6286
Epoch 24/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6627 - loss: 0.5434 - val_accuracy: 0.6200 - val_loss: 0.6265
Epoch 25/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6660 - loss: 0.5403 - val_accuracy: 0.6240 - val_loss: 0.6237
Epoch 26/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6640 - loss: 0.5371 - val_accuracy: 0.6240 - val_loss: 0.6208
Epoch 27/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6640 - loss: 0.5343 - val_accuracy: 0.6280 - val_loss: 0.6157
Epoch 28/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6660 - loss: 0.5309 - val_accuracy: 0.6220 - val_loss: 0.6157
Epoch 29/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6687 - loss: 0.5282 - val_accuracy: 0.6240 - val_loss: 0.6124
Epoch 30/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6673 - loss: 0.5250 - val_accuracy: 0.6220 - val_loss: 0.6107
Epoch 31/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.5214 - val_accuracy: 0.6120 - val_loss: 0.6082
Epoch 32/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.5179 - val_accuracy: 0.6120 - val_loss: 0.6049
Epoch 33/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.5149 - val_accuracy: 0.6160 - val_loss: 0.5990
Epoch 34/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.5106 - val_accuracy: 0.6160 - val_loss: 0.5969
Epoch 35/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6673 - loss: 0.5072 - val_accuracy: 0.6140 - val_loss: 0.5952
Epoch 36/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6640 - loss: 0.5034 - val_accuracy: 0.6200 - val_loss: 0.5913
Epoch 37/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.4992 - val_accuracy: 0.6200 - val_loss: 0.5883
Epoch 38/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6747 - loss: 0.4955 - val_accuracy: 0.6240 - val_loss: 0.5844
Epoch 39/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6733 - loss: 0.4922 - val_accuracy: 0.6260 - val_loss: 0.5823
Epoch 40/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6767 - loss: 0.4884 - val_accuracy: 0.6340 - val_loss: 0.5768
Epoch 41/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6780 - loss: 0.4846 - val_accuracy: 0.6400 - val_loss: 0.5719
Epoch 42/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6767 - loss: 0.4807 - val_accuracy: 0.6400 - val_loss: 0.5685
Epoch 43/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6773 - loss: 0.4771 - val_accuracy: 0.6380 - val_loss: 0.5637
Epoch 44/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6807 - loss: 0.4735 - val_accuracy: 0.6400 - val_loss: 0.5601
Epoch 45/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6807 - loss: 0.4698 - val_accuracy: 0.6340 - val_loss: 0.5567
Epoch 46/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6853 - loss: 0.4657 - val_accuracy: 0.6320 - val_loss: 0.5527
Epoch 47/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6873 - loss: 0.4620 - val_accuracy: 0.6340 - val_loss: 0.5499
Epoch 48/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6920 - loss: 0.4584 - val_accuracy: 0.6320 - val_loss: 0.5457
Epoch 49/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6987 - loss: 0.4543 - val_accuracy: 0.6380 - val_loss: 0.5415
Epoch 50/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7027 - loss: 0.4506 - val_accuracy: 0.6380 - val_loss: 0.5392
Epoch 51/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7060 - loss: 0.4471 - val_accuracy: 0.6420 - val_loss: 0.5348
Epoch 52/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7073 - loss: 0.4434 - val_accuracy: 0.6440 - val_loss: 0.5330
Epoch 53/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7160 - loss: 0.4402 - val_accuracy: 0.6480 - val_loss: 0.5295
Epoch 54/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7147 - loss: 0.4366 - val_accuracy: 0.6480 - val_loss: 0.5264
Epoch 55/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7213 - loss: 0.4335 - val_accuracy: 0.6540 - val_loss: 0.5226
Epoch 56/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7213 - loss: 0.4299 - val_accuracy: 0.6580 - val_loss: 0.5179
Epoch 57/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7253 - loss: 0.4262 - val_accuracy: 0.6700 - val_loss: 0.5156
Epoch 58/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7327 - loss: 0.4234 - val_accuracy: 0.6720 - val_loss: 0.5128
Epoch 59/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7300 - loss: 0.4199 - val_accuracy: 0.6760 - val_loss: 0.5091
Epoch 60/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7367 - loss: 0.4164 - val_accuracy: 0.6740 - val_loss: 0.5060
Epoch 61/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7407 - loss: 0.4133 - val_accuracy: 0.6820 - val_loss: 0.5030
Epoch 62/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7453 - loss: 0.4101 - val_accuracy: 0.6880 - val_loss: 0.4991
Epoch 63/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7453 - loss: 0.4074 - val_accuracy: 0.6860 - val_loss: 0.4956
Epoch 64/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7493 - loss: 0.4039 - val_accuracy: 0.6900 - val_loss: 0.4924
Epoch 65/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7493 - loss: 0.4009 - val_accuracy: 0.6960 - val_loss: 0.4890
Epoch 66/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7520 - loss: 0.3980 - val_accuracy: 0.7000 - val_loss: 0.4859
Epoch 67/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7580 - loss: 0.3947 - val_accuracy: 0.7060 - val_loss: 0.4824
Epoch 68/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7613 - loss: 0.3913 - val_accuracy: 0.7060 - val_loss: 0.4785
Epoch 69/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7667 - loss: 0.3883 - val_accuracy: 0.7100 - val_loss: 0.4746
Epoch 70/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.3843 - val_accuracy: 0.7080 - val_loss: 0.4711
Epoch 71/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7847 - loss: 0.3809 - val_accuracy: 0.7160 - val_loss: 0.4674
Epoch 72/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7860 - loss: 0.3775 - val_accuracy: 0.7240 - val_loss: 0.4646
Epoch 73/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7860 - loss: 0.3746 - val_accuracy: 0.7240 - val_loss: 0.4618
Epoch 74/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7973 - loss: 0.3707 - val_accuracy: 0.7360 - val_loss: 0.4571
Epoch 75/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.3676 - val_accuracy: 0.7360 - val_loss: 0.4540
Epoch 76/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8093 - loss: 0.3638 - val_accuracy: 0.7360 - val_loss: 0.4521
Epoch 77/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8100 - loss: 0.3603 - val_accuracy: 0.7440 - val_loss: 0.4488
Epoch 78/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8127 - loss: 0.3566 - val_accuracy: 0.7480 - val_loss: 0.4455
Epoch 79/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8200 - loss: 0.3533 - val_accuracy: 0.7520 - val_loss: 0.4430
Epoch 80/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8227 - loss: 0.3495 - val_accuracy: 0.7640 - val_loss: 0.4405
Epoch 81/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8293 - loss: 0.3459 - val_accuracy: 0.7760 - val_loss: 0.4372
Epoch 82/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8293 - loss: 0.3423 - val_accuracy: 0.7760 - val_loss: 0.4320
Epoch 83/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8387 - loss: 0.3383 - val_accuracy: 0.7820 - val_loss: 0.4263
Epoch 84/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8447 - loss: 0.3343 - val_accuracy: 0.7800 - val_loss: 0.4245
Epoch 85/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8447 - loss: 0.3299 - val_accuracy: 0.7880 - val_loss: 0.4182
Epoch 86/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8460 - loss: 0.3248 - val_accuracy: 0.7880 - val_loss: 0.4148
Epoch 87/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8573 - loss: 0.3205 - val_accuracy: 0.7940 - val_loss: 0.4084
Epoch 88/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8573 - loss: 0.3142 - val_accuracy: 0.7980 - val_loss: 0.4025
Epoch 89/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3094 - val_accuracy: 0.8020 - val_loss: 0.3978
Epoch 90/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8720 - loss: 0.3034 - val_accuracy: 0.8100 - val_loss: 0.3913
Epoch 91/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8800 - loss: 0.2977 - val_accuracy: 0.8140 - val_loss: 0.3847
Epoch 92/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8880 - loss: 0.2919 - val_accuracy: 0.8220 - val_loss: 0.3759
Epoch 93/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8980 - loss: 0.2855 - val_accuracy: 0.8400 - val_loss: 0.3692
Epoch 94/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9027 - loss: 0.2791 - val_accuracy: 0.8460 - val_loss: 0.3603
Epoch 95/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9073 - loss: 0.2718 - val_accuracy: 0.8440 - val_loss: 0.3545
Epoch 96/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9153 - loss: 0.2655 - val_accuracy: 0.8580 - val_loss: 0.3464
Epoch 97/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 0.2583 - val_accuracy: 0.8580 - val_loss: 0.3411
Epoch 98/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9220 - loss: 0.2513 - val_accuracy: 0.8580 - val_loss: 0.3352
Epoch 99/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9260 - loss: 0.2460 - val_accuracy: 0.8640 - val_loss: 0.3273
Epoch 100/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9313 - loss: 0.2405 - val_accuracy: 0.8660 - val_loss: 0.3221

## Evaluate the model

In [25]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8660 - loss: 0.3221
Test Loss: 0.32206135988235474
Test Accuracy: 0.8659999966621399

## Save the weights

In [26]:
model.save_weights("mobile_price_ann.weights.h5")

In [28]:
import os

os.listdir()

['.config', '.ipynb_checkpoints', 'sample_data', 'mobile_price_ann.weights.h5']